### ISSUE TITLE
Sorry, about chromium.

### ISSUE THREAD

**Issue by Rassska** [jdoerrie/XPokerEval#1]
Hi, Jan Wilken Dörrie!

I want to apologize for this trick, but still have a huge amount of desire to ask you a question about searching panel system in chromium. 

Here I wanna know which file/method would be used for exploring this kind of request from user?
 Currently, I'm looking for[ this file](https://github.com/chromium/chromium/blob/master/components/history/core/browser/browsing_history_service.cc), but still have no idea about the exact method which will process requests from users in search panel of history tab.
 Thanks a lot for you response, have a good time!
 
![browse_history_panel](https://user-images.githubusercontent.com/73281386/119373454-1a3f5400-bcc1-11eb-91bb-6fa1aa72ac6b.png)

**Comment by jdoerrie** [comment]
Hi Rasul, kudos for this trick to reach me :D 

Next time I'd suggest you try writing to chromium-discuss@chromium.org, which is a mailing list we have to handle this kind of requests. Also I would advise you to use Chromium's [Code Search](https://source.chromium.org/chromium/chromium/src) to explore the codebase. While we do mirror the code and commits to GitHub, Code Search is quite a bit more powerful, and used by effectively all Chromium developers.

That said, let me try to answer your question to the best of my abilities: The screenshot you shared is taken from chrome://history, right? The UI for that is written in HTML and JavaScript, and the code lives in [`chrome/browser/resources/history/`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/history/). 

Looking around a bit, it seems like [`query_manager.js`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/history/query_manager.js) is relevant, in particular [`queryHistory_`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/history/query_manager.js;l=85;drc=d664f18300ab8ef1dc067ccbb7d9864c666ac661). This invokes [`browserService.queryHistory`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/resources/history/browser_service.js;l=115;drc=5867d9513ed07970080a4a2044a4e4fe5caa17e6) which in turn sends the `'queryHistory'` command to the backend. The [backend](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/history/browsing_history_handler.cc) is written in C++, and registers a callback for this message [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/history/browsing_history_handler.cc;l=319;drc=cf86a6f2b7bb37d9c09feea1c5e3abd7b13574ee). [`BrowsingHistoryHandler::HandleQueryHistory`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/history/browsing_history_handler.cc;l=353;drc=82e859c76f49d28b101d4fb8217635c5ccaa6112) then performs a couple of sanity checks, and invokes [`BrowsingHistoryService::QueryHistory`](https://source.chromium.org/chromium/chromium/src/+/main:components/history/core/browser/browsing_history_service.cc;l=229;drc=82e859c76f49d28b101d4fb8217635c5ccaa6112) from [`BrowsingHistoryHandler::SendHistoryQuery`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/history/browsing_history_handler.cc;l=389;drc=82e859c76f49d28b101d4fb8217635c5ccaa6112).

This is the file you had found already. `QueryHistory` then calls [`QueryHistoryInternal`](https://source.chromium.org/chromium/chromium/src/+/main:components/history/core/browser/browsing_history_service.cc;l=240;drc=82e859c76f49d28b101d4fb8217635c5ccaa6112), which can query the local history, or even perform a web request to fetch history that was synced. Either of these code paths eventually calls [` BrowsingHistoryService::ReturnResultsToDriver`](https://source.chromium.org/chromium/chromium/src/+/main:components/history/core/browser/browsing_history_service.cc;l=570;drc=82e859c76f49d28b101d4fb8217635c5ccaa6112), eventually invoking [`BrowsingHistoryHandler::OnQueryComplete`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/ui/webui/history/browsing_history_handler.cc;l=474;drc=82e859c76f49d28b101d4fb8217635c5ccaa6112). This then finally constructs a JSON like object with the results, and passes it back to the JavaScript frontend, where it is displayed to the user.

I hope this helps :) In case you have follow-up questions, please do direct them to chromium-discuss@chromium.org, as I only have a high level understanding of how the history lookup works.

**Comment by Rassska** [comment]
Thank you so much, cheered me up today! So much useful information!
